---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@4797d9f93b2636e75dda38232aac206ac161f7e5 # master
    permissions:
      contents: write
