---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@992c769d64bb0306810e3fa8db52055a55e31b3a # master
    permissions:
      contents: write
